### PR TITLE
Resolving librdkafka and LightGBM compatibility issues with macOS M1/M2 chips

### PR DESCRIPTION
**Pull request by gao-hongnan**
This PR addresses the issue #1 that was raised concerning problems with installing `hopswork` on machines with macOS M1/M2 chips. The root cause was with `librdkafka`.

Changes made in this PR:

1. Added a script to check the version of `librdkafka` installed on the system. If it is not installed or the installed version does not match the required version (currently `1.9.2`), it fetches the source code and builds it from source. See [here](https://community.hopsworks.ai/t/ssl-handshake-failed-on-macos-hopsworks-serverless/886/3) for the required version.

In addition, installing `LightGMB` requires `cmake` and `libomp`, and the script checks if `cmake` and `libomp` are installed on the system. If they are not, it proceeds to install them.

All of these checks and installations are performed only if the machine's architecture is detected as `arm64`, i.e., if the machine is running on an M1/M2 chip. Otherwise, these steps are skipped.

This approach ensures that our users running macOS with M1/M2 chips can seamlessly set up and use our software without encountering the issues reported.

### CODE REVIEW

**Comment by iusztinpaul** [comment]
Before accepting the PR, could you give a few examples of how & when to call the script? As we have a different Poetry environment for every module, I haven't 100% understood how it is connected to the `pyproject.toml` and `poetry.lock` files. 

An example for sure will clarify this.

**Comment by gao-hongnan** [comment]
> Before accepting the PR, could you give a few examples of how & when to call the script? As we have a different Poetry environment for every module, I haven't 100% understood how it is connected to the `pyproject.toml` and `poetry.lock` files.
> 
> An example for sure will clarify this.

Thanks for reviewing. When I tried to follow the installation via:

```bash
poetry shell
poetry install
```

I ran into the same error mentioned in #1, following the fix proposed by the author, I just modularized the custom installation into a bash script. So the way to run it is to run the script first.

```bash
bash scripts/poetry_install.sh
```

and then run the poetry commands as per usual.

**Comment by iusztinpaul** [comment]
And will it know to install the requirements from the `pyproject.toml` file from the current directory?

I am asking this because we have a different `pyproject.toml` file in every module.

**Comment by gao-hongnan** [comment]
> And will it know to install the requirements from the `pyproject.toml` file from the current directory?
> 
> I am asking this because we have a different `pyproject.toml` file in every module.

The current script does not automatically handle the installation of Python requirements from the `pyproject.toml` file in your current directory. This means that one can continue using your `poetry` commands as usual afterwards. This script only solves the particular issues related to the `librdkafka` and `lightgbm` packages on M1 chips.

**Comment by iusztinpaul** [comment]
I see, could you please rename the script to something like ‘install_poetry_macos_m_chips_sh’ ?

Afterward, I will accept the PR.

Thanks!

**Comment by gao-hongnan** [comment]
> I see, could you please rename the script to something like ‘install_poetry_macos_m_chips_sh’ ?
> 
> Afterward, I will accept the PR.
> 
> Thanks!

Thanks, have renamed the script to `install_poetry_macos_m1_chip.sh`.

**Pull request merged**
